volumes:
  pgdata:
services:
  # Postgres
  postgresql:
    image: postgres
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
networks:
  webnet:
    driver: overlay
    attachable: true
